name: Update Awesome Papers

permissions:
  contents: write  # allows pushing commits
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: "*/5 * * * *"  # runs every 5 minutes
  workflow_dispatch:      # allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # use PAT here if GITHUB_TOKEN fails

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Run Notion fetch script
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: python generate_awesome_papers.py

    - name: Commit and push changes if any
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md

        # Check if there are any changes
        if ! git diff --cached --quiet; then
          git commit -m "Auto-update awesome papers from Notion"
          git push
        else
          echo "No changes to commit"
        fi
